language: go

go:
  - 1.5

env:
  - "MY_GOOS=linux MY_GOARCH=amd64"
  - "MY_GOOS=darwin MY_GOARCH=amd64"
  - "MY_GOOS=windows MY_GOARCH=amd64"
  - "MY_GOOS=windows MY_GOARCH=386"

before_install:
# workaround for travis-ci/gimme#42
  - curl -o go.tar.gz -sL https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz
  - tar -C $HOME -xf go.tar.gz
  - rm go.tar.gz
  - export GOROOT="${HOME}/go"
  - export PATH="${GOROOT}/bin:${PATH}"
  - export GOOS="${MY_GOOS}"
  - export GOARCH="${MY_GOARCH}"
# end of workaround ###

install:
  - go get -d -t ./...
  - "if test $GOOS.$GOARCH = linux.amd64; then npm install; fi"

script:
  - go install -v ./...
  - "if test $GOOS.$GOARCH = linux.amd64; then npm test; fi"

notifications:
  irc:
    channels:
      # encrypt the channel name so that user forks don't spam IRC
      # decrypted version is "irc.mozilla.org#taskcluster-bots"
      # see https://github.com/travis-ci/travis-ci/issues/1094
      - secure: "iWVuoaXyzNFjdDPlo/Jac04n+4yMlcgW0uEMLvF79Z5gqe/K+kbD5iy0lCo9wUIVM9O03/8K+7mNS/SlYMiOpmziyAhEKi3X4CFErNuwy1pyriLJrZZScOqGPKkuP7+m+BBCjVXoyFRYXYQ7SncQsLlE3wtJvA7dNNSLCGUg5ys="
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"

before_deploy:
  - "source .travis_rename_releases.sh"

deploy:
  provider: releases
  api_key:
    secure: fwTLVhfs/5ioduZQdj49n6/4rn7AYcAyAeUcRdA/ezhWAj1KsT6qU7snBdhfEwpo+TaVbLq6SwpknLXax9d6mESs7EOL9EmEt73ocw0OG1omfjrBn5mQuuVIiUky5qhIZy+qufiqUq3iVe/V8cyZSGqcPRbazLIhAAKR0r44dys=
  file:
    - "${RELEASE_FILE}"
  on:
    repo: taskcluster/livelog
    tags: true
  skip_cleanup: true
